# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Quality gate npm pre-build

on:
  workflow_call:
    inputs:
      projectService:
        required: true
        type: string
    #   skipTests:
    #     description: 'skipTests'
    #     type: string
    #   sonarQubeSC:
    #     description: 'sonarQubeSC'
    #     type: string

env:
  feedName: EcoviumCommon
  containerRegistrySC: acrsimplechaindevSC
  sonarQubeSC: SonarQubeSC
  npmTestsAvailable: false
  packageJsonPath: ''
  group: acr-devops
  sonarQubeEndpointUrl: http://simplechain-sq-dev.germanywestcentral.cloudapp.azure.com
  sonarQubeApiUserToken: squ_53e25f1abe6db9259095570120052adad9be4380
  sonarQubeAvailable: ''
  RunCypressGuiTests: ''
  buildConfiguration: Release
  TAG_NAME: ${{ inputs.buildVersion }}-${{ github.run_id }}.${{ github.ref_name }}.${{ github.sha }}
  SERVICE_NAME: ${{ inputs.serviceName }}

jobs:

  calling-workflow-quality-gate-pre-build:
    uses: MhpTransport/Ecovium.Github.Actions/.github/workflows/quality-gate-pre-build-template.yml@develop
    with:
      projectService: ${{ inputs.projectService }}

  quality-gate-npm-prebuild:
    needs: calling-workflow-quality-gate-pre-build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Sonar Prepare Analysis
      uses: docker://sonarsource/sonar-scanner-cli:latest
      with:
        args: >
          -Dsonar.projectKey=${{ inputs.projectService }}
          -Dsonar.host.url=${{ env.sonarQubeEndpointUrl }}
          -Dsonar.token=${{ env.sonarQubeApiUserToken }}
          -Dsonar.sources=.
          -Dsonar.javascript.lcov.reportPaths='${{ github.workspace }}/**/ClientApp/coverage/**/lcov-report/lcov.info'
