# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Quality gate npm pre-build

on:
  workflow_call:
    # inputs:
    #   skipTests:
    #     description: 'skipTests'
    #     type: string
    #   sonarQubeSC:
    #     description: 'sonarQubeSC'
    #     type: string

jobs:

  build:
    steps:
    - uses: actions/checkout@v4
